name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    if: github.repository == 'tgirlcloud/beapkgs'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Update lockfile
        run: nix flake update

      - name: Update packages
        run: nix run .#update

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: bump flake inputs"
